# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BNMI 
email: cci@gu.se
description: Welcome to BNMI 2025, Gothenburg

#domain: xfolka.github.io
#baseurl:  ""
#url: https://xfolka.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  xfolka
#permalink: /:title/

#cover: "/assets/header_image.jpg"
feature_iamge: ./assets/hero2.png
logo: /assets/bnmi.png

symposium_registration_link: https://www.lyyti.fi/reg/BNMI_2025_Symposium_9129
workshops_registration_link: https://forms.office.com/e/nj4R3a3bF6?origin=lprLink

collections:
  abstracts:
    output: true
  sessions:
    output: true
  speakers:
    output: true
  hotels:
    output: true

# Build settings
remote_theme: daviddarnes/alembic@main
#theme: centrarium
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-seo-tag
#  - EmailSender

# Build settings
markdown: kramdown
inter_post_navigation: false
highlights_theme: "monokai-sublime"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
#   Twitter: https://twitter.com/DavidDarnes
#   LinkedIn: https://www.linkedin.com/in/daviddarnes
#   GitHub: https://github.com/daviddarnes
#   link: https://darn.es
#   RSS: /feed.xml  

# sharing_links:
#   Twitter: "#1DA1F2"
#   facebook: "#3B5998"
#   LinkedIn: "#0077B5"



#  Pinterest: "#BD081C"
#  tumblr: "#36465D"
#  Reddit: "#FF4500"
#  HackerNews: "#ff6600"
#  DesignerNews: "#2D72D9"
#  Email: true

navigation_header:
- title: Home
  url: /home/
- title: Registration
  url: /registration/
- title: Programme
  url: /programme/
- title: Speakers
  url: /speakers/
- title: Venue
  url: /venue/
- title: Travel
  url: /travel/
- title: Workshops
  url: /workshops/
- title: Organizers
  url: /organizers/
- title: Sponsors
  url: /sponsors/

# - title: Abstract Submission
#   url: /abstracts/

navigation_footer:
- title: CCI
  url: https://www.gu.se/en/core-facilities/infrastructure-at-core-facilities/centre-for-cellular-imaging
- title: Search
  url: /search/
- title: Registration
  url: /registration/
- title: Workshops
  url: /workshops/



custom_fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
    - https://fonts.googleapis.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Questrial&display=swap

email_settings:
  smtp_server: smtpgw.gu.se
  smtp_port: 587
  smtp_username: ""
  smtp_password: ""
  from_email: bnmi_abstract@gu.se
